### ISSUE TITLE
Add ability to edit donation in Step 2

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/donation-block-for-stripe#12]
## Details

Right now there's no way to edit a donation after moving to the payment step. We should make this process easier than having the donor refresh the page (which many likely won't know how to do).

**Comment by DevinWalker** [comment]
@mathetos @JasonTheAdams which one do you like more? 

1. Subtle edit

<img width="648" alt="2022-03-28_11-22-11" src="https://user-images.githubusercontent.com/1571635/160462237-b6ad09a0-d48b-49d1-8b83-e77440b6fe47.png">

2. Less subtle edit

<img width="639" alt="2022-03-28_11-22-01" src="https://user-images.githubusercontent.com/1571635/160462216-521165dd-d4bf-4b87-9c54-d496949a1dfe.png">


3. Shopping cart kinda feel

<img width="537" alt="2022-03-28_11-22-30" src="https://user-images.githubusercontent.com/1571635/160462256-103110b8-8fb9-4a8c-bb94-5fb8778fc650.png">

**Comment by JasonTheAdams** [comment]
Oh man. Honestly, I like all three of these. As not to draw too much attention, I think I like Option 2 the best.

**Comment by mathetos** [comment]
I like #3 a lot.

**Comment by JasonTheAdams** [comment]
I see. Then there's only one way to settle this.

![lets arm wrestle](https://media.giphy.com/media/l2JhAI2gbnYLJ1vgY/giphy.gif)

**Comment by JasonTheAdams** [comment]
I like 3 as well. In lieu of a a "donation receipt" I think that's a good approach.

**Comment by DevinWalker** [comment]
I like 3 too but the heart icon kinda feels weird in place of an actual product image. Maybe we can think of something better for that.
