### ISSUE TITLE
Plugin should adhere to the block directory guidelines to be included

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/donation-block-for-stripe#17]
## Additional Context

Currently the plugin violates the PHP maximum allowed when running it through the validator. There are also a few other recommendations that we should apply.

Block Plugin Checker: https://wordpress.org/plugins/developers/block-plugin-validator/

**Block Directory Guidelines:**
- GitHub Repo: https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md
- Make Post: https://make.wordpress.org/meta/2019/12/06/block-directory-plugin-guidelines/

Release 1.0.0 recommendations:

<img width="935" alt="2022-03-09_09-08-02" src="https://user-images.githubusercontent.com/1571635/157493638-044a5300-7edd-4cbe-a728-8e0338986d82.png">

## Acceptance Criteria

-   [ ] PHP is reduced to guideline's recommendations  
- [ ] Translation scripts work as expected
- [ ] "block" is added as a tag

**Comment by kjohnson** [comment]
The Stripe PHP SDK alone is half of the included PHP. We could trim that significantly with a purpose built integration.

**Comment by DevinWalker** [comment]
We're now in the block directory - ditched the Stripe SDK and Strauss... see PR above.
